### ISSUE TITLE
ES6 iterators proposal

### ISSUE THREAD

**Issue by glebcha** [vasanthk/js-bits#12]
Maybe [gist](https://gist.github.com/glebcha/7382ee3aa9b3292fb944) can be merged.

**Comment by vasanthk** [comment]
@glebcha This is nice.
I have another [repo](https://github.com/vasanthk/js-utils/tree/master/js) where I add in utils functions and I think an objectIterator.js would fit in well there/
What do you think?
Could you send in a PR to the other repo if that's ok?

**Comment by glebcha** [comment]
@vasanthk Sure.

**Comment by vasanthk** [comment]
Cool, thank you :)
Closing this.
