### ISSUE TITLE
Misconception about pass by value

### ISSUE THREAD

**Issue by cstruct** [vasanthk/js-bits#14]
In your description about pass by value vs pass by reference I believe you confuse the concepts of value types and shallow copying. The `Array.prototype.slice` function does a shallow of the array, meaning a new array is constructed but with references to the objects of the original array. I believe this description is both factually incorrect and confusing to beginners.

**Comment by vasanthk** [comment]
@cstruct That's a good point. I knew about it, but forgot to mention it.
Would you like to send in a PR for that? Or i can add it too..

**Comment by cstruct** [comment]
Thank you for a quick response. I reread my message and noticed I feel it is a bit rude, I apologize for that. For future reference It It is clear from your example that you grasp these concepts. I understand it must be hard to make these examples both descriptive and understandable. I would be happy to submit a PR but can't promise it will be any better! :smile: 

Will try to submit something tomorrow.

Have a nice weekend! :fireworks:

**Comment by vasanthk** [comment]
@cstruct Sure, no problem. I understand your sentiment about beginners finding it confusing.
I created this repo more as a personal reference. But it blew up over the past week and I am glad others found it helpful. So, I'll try my best to explain things better.
