### ISSUE TITLE
array-concat-push.js push.apply is bad advice for performance

### ISSUE THREAD

**Issue by vird** [vasanthk/js-bits#15]
https://jsperf.com/array-prototype-push-apply-vs-concat/81

But that it's better on small arrays.
https://jsperf.com/array-prototype-push-apply-vs-concat/20

**Comment by vasanthk** [comment]
Thanks. I picked that up from the comments in http://stackoverflow.com/a/5081471/1672655
Apparently, it used to be real fast in V8, But the comment is ~4 yrs old and I can only assume that V8 engine has been optimized and changed over time. 
Have removed the comment.
