### ISSUE TITLE
-1 should be the last element for splice() function

### ISSUE THREAD

**Issue by PinkyJie** [vasanthk/js-bits#18]
I found a issue on https://github.com/vasanthk/js-bits/blob/master/js/array-slice-splice.js

<img width="328" alt="2016-03-28 11 23 46" src="https://cloud.githubusercontent.com/assets/551329/14081227/3e250718-f53c-11e5-9373-7fc4ad79879b.png">

Which is wrong, -1 should be 20 in the above example.

**Comment by vasanthk** [comment]
Thanks @PinkyJie :+1:

**Comment by cangku** [comment]
:+1:
