### ISSUE TITLE
Maybe a chinese version?

### ISSUE THREAD

**Issue by ecmadao** [vasanthk/js-bits#23]
Hey @vasanthk , thanks for your contribution.

Some Chinese JavaScript beginners or developers are not good at English, so I started to translation this repository some days ago, and will translate at least one file per day.

But maybe I need your permission to keep on translating? And I'll be proud to be an official cn-doc of your repository.

You can find Chinese version in here: [js-bits-cn](https://github.com/ecmadao/js-bits-cn).

THX.

**Comment by cangku** [comment]
I have an incomplete version, English is not very good, did not finish learning  https://github.com/cangku/js-bits-zh

**Comment by vasanthk** [comment]
@ecmadao and @cangku With pleasure :)
Feel free to send in a PR so that I can link it to the README as well for easy discoverability.

**Comment by ecmadao** [comment]
@vasanthk 
Cool. THX!

**Comment by vasanthk** [comment]
@ecmadao Had a look into the repo. Great work 🎉
